openapi: 3.0.3
info:
  title: Redmine OpenAPI Specification
  version: 6.0.0
servers:
  - url: http://127.0.0.1:3000
paths:
  /custom_fields.json:
    $ref: "./custom_fields.yml#/paths/~1custom_fields.json"
  /groups.json:
    $ref: "./groups.yml#/paths/~1groups.json"
  /groups/{id}.json:
    $ref: "./groups.yml#/paths/~1groups~1{id}.json"
  /groups/{id}/users.json:
    $ref: "./groups.yml#/paths/~1groups~1{id}~1users.json"
  /groups/{id}/users/{user_id}.json:
    $ref: "./groups.yml#/paths/~1groups~1{id}~1users~1{user_id}.json"
  /issues.json:
    $ref: "./issues.yml#/paths/~1issues.json"
  /issues/{id}.json:
    $ref: "./issues.yml#/paths/~1issues~1{id}.json"
  /issues/{issue_id}/relations.json:
    $ref: "./issue_relations.yml#/paths/~1issues~1{issue_id}~1relations.json"
  /issues/{issue_id}/time_entries.json:
    $ref: "./timelog.yml#/paths/~1issues~1{issue_id}~1time_entries.json"
  /issue_categories/{id}.json:
    $ref: "./issue_categories.yml#/paths/~1issue_categories~1{id}.json"
  /journals/{id}.json:
    $ref: "./journals.yml#/paths/~1journals~1{id}.json"
  /memberships/{id}.json:
    $ref: "./members.yml#/paths/~1memberships~1{id}.json"
  /news.json:
    $ref: "./news.yml#/paths/~1news.json"
  /news/{id}.json:
    $ref: "./news.yml#/paths/~1news~1{id}.json"
  /projects.json:
    $ref: "./projects.yml#/paths/~1projects.json"
  /projects/{id}.json:
    $ref: "./projects.yml#/paths/~1projects~1{id}.json"
  /projects/{id}/archive.json:
    $ref: "./projects.yml#/paths/~1projects~1{id}~1archive.json"
  /projects/{id}/unarchive.json:
    $ref: "./projects.yml#/paths/~1projects~1{id}~1unarchive.json"
  /projects/{project_id}/issues.json:
    $ref: "./issues.yml#/paths/~1projects~1{project_id}~1issues.json"
  /projects/{project_id}/issue_categories.json:
    $ref: "./issue_categories.yml#/paths/~1projects~1{project_id}~1issue_categories.json"
  /projects/{project_id}/memberships.json:
    $ref: "./members.yml#/paths/~1projects~1{project_id}~1memberships.json"
  /projects/{project_id}/news.json:
    $ref: "./news.yml#/paths/~1projects~1{project_id}~1news.json"
  /projects/{project_id}/time_entries.json:
    $ref: "./timelog.yml#/paths/~1projects~1{project_id}~1time_entries.json"
  /projects/{project_id}/versions.json:
    $ref: "./versions.yml#/paths/~1projects~1{project_id}~1versions.json"
  /projects/{project_id}/wiki.json:
    $ref: "./wiki.yml#/paths/~1projects~1{project_id}~1wiki.json"
  /projects/{project_id}/wiki/index.json:
    $ref: "./wiki.yml#/paths/~1projects~1{project_id}~1wiki~1index.json"
  /projects/{project_id}/wiki/{id}.json:
    $ref: "./wiki.yml#/paths/~1projects~1{project_id}~1wiki~1{id}.json"
  /projects/{project_id}/wiki/{id}/{version}.json:
    $ref: "./wiki.yml#/paths/~1projects~1{project_id}~1wiki~1{id}~1{version}.json"
  /relations/{id}.json:
    $ref: "./issue_relations.yml#/paths/~1relations~1{id}.json"
  /roles.json:
    $ref: "./roles.yml#/paths/~1roles.json"
  /roles/{id}.json:
    $ref: "./roles.yml#/paths/~1roles~1{id}.json"
  /time_entries.json:
    $ref: "./timelog.yml#/paths/~1time_entries.json"
  /time_entries/{id}.json:
    $ref: "./timelog.yml#/paths/~1time_entries~1{id}.json"
  /users.json:
    $ref: "./users.yml#/paths/~1users.json"
  /users/{id}.json:
    $ref: "./users.yml#/paths/~1users~1{id}.json"
  /versions/{id}.json:
    $ref: "./versions.yml#/paths/~1versions~1{id}.json"
components:
  schemas:
    custom_field:
      type: object
      properties:
        id:
          type: integer
          description: The ID of the custom field.
        name:
          type: string
          description: The name of the custom field.
        multiple:
          type: boolean
          description: Whether the custom field can have multiple values.
        value: {}
    custom_field_values:
      type: object
      description: |
        The values of the custom fields.
      additionalProperties: true
    errors:
      description: |
        A list of errors that occurred during the request.
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
    error:
      description: |
        A single error that occurred during the request.
      type: object
      properties:
        status:
          type: integer
          description: The HTTP status code of the error.
        error:
          type: string
          description: A description of the error.
  responses:
    no_content:
      description: not provided
    unprocessable_entity:
      description: |
        The request was well-formed but was unable to be followed due to semantic errors.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errors"
    error:
      description: |
        An error occurred while processing the request.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
  parameters:
    # User Impersonation
    X-Redmine-Switch-User:
      name: X-Redmine-Switch-User
      in: header
      description: |
        This only works when using the API with an administrator account,
        this header will be ignored when using the API with a regular user account.
      schema:
        type: string
    # Collection resources and paginatio
    X-Redmine-Nometa:
      name: X-Redmine-Nometa
      in: header
      description: |
        If set to 1, the response will not include metadata information.
      schema:
        type: integer
        enum: [1]
    nometa:
      name: nometa
      in: query
      description: |
        If set to 1, the response will not include metadata information.
      schema:
        type: integer
        enum: [1]
    pagination:
      name: pagination
      in: query
      description: |
        Pagination parameters to control the number of items returned in the response.
        If not specified, it defaults to 25 items per page.
      schema:
        type: object
        properties:
          offset:
            type: integer
            description: |
              The offset of the first object to retrieve
              If not specified, it defaults to 0.
            default: 0
          limit:
            type: integer
            description: |
              The number of items to be present in the response.
              If not specified, it defaults to 25.
            default: 25
            maximum: 100
          nometa:
            type: integer
            description: |
              If set to 1, the response will not include pagination information.
            enum: [1]
  securitySchemes:
    # Authentication
    ApiKeyHeaderAuth:
      type: apiKey
      in: header
      name: X-Redmine-API-Key
    ApiKeyQueryAuth:
      type: apiKey
      in: query
      name: key
    BasicAuth:
      type: http
      scheme: basic
security:
  - ApiKeyHeaderAuth: []
  - ApiKeyQueryAuth: []
  - BasicAuth: []
tags:
  - name: custom_fields
    description: custom_fields_controller's API
  - name: groups
    description: groups_controller's API
  - name: issues
    description: issues_controller's API
  - name: issue_categories
    description: issue_categories_controller's API
  - name: issue_relations
    description: issue_relations_controller's API
  - name: journals
    description: journals_controller's API
  - name: members
    description: members_controller's API
  - name: news
    description: news_controller's API
  - name: projects
    description: projects_controller's API
  - name: roles
    description: roles_controller's API
  - name: timelog
    description: timelog_controller's API
  - name: users
    description: users_controller's API
  - name: versions
    description: versions_controller's API
  - name: wiki
    description: wiki_controller's API
