openapi: 3.0.3
info:
  title: Redmine OpenAPI Specification
  version: 6.0.0
servers:
  - url: http://127.0.0.1:3000
paths:
  /projects.json:
    $ref: "./projects.yml#/paths/~1projects.json"
  /projects/{id}.json:
    $ref: "./projects.yml#/paths/~1projects~1{id}.json"
  /projects/{id}/archive.json:
    $ref: "./projects.yml#/paths/~1projects~1{id}~1archive.json"
  /projects/{id}/unarchive.json:
    $ref: "./projects.yml#/paths/~1projects~1{id}~1unarchive.json"
  /users.json:
    $ref: "./users.yml#/paths/~1users.json"
  /users/{id}.json:
    $ref: "./users.yml#/paths/~1users~1{id}.json"
components:
  schemas:
    custom_field:
      type: object
      properties:
        id:
          type: integer
          description: The ID of the custom field.
        name:
          type: string
          description: The name of the custom field.
        multiple:
          type: boolean
          description: Whether the custom field can have multiple values.
        value:
          oneOf:
            - type: array
              items:
                type: string
                description: The value of the custom field when it can have multiple values.
            - type: string
              description: The value of the custom field when it has a single value.
    custom_field_values:
      type: object
      description: |
        The values of the custom fields.
      additionalProperties:
        oneOf:
          - type: array
            items:
              type: string
              description: The value of the custom field when it can have multiple values.
          - type: string
            description: The value of the custom field when it has a single value.
    errors:
      description: |
        A list of errors that occurred during the request.
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
    error:
      description: |
        A single error that occurred during the request.
      type: object
      properties:
        status:
          type: integer
          description: The HTTP status code of the error.
        error:
          type: string
          description: A description of the error.
  responses:
    no_content:
      description: not provided
    unprocessable_entity:
      description: |
        The request was well-formed but was unable to be followed due to semantic errors.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errors"
    error:
      description: |
        An error occurred while processing the request.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
  parameters:
    # User Impersonation
    X-Redmine-Switch-User:
      name: X-Redmine-Switch-User
      in: header
      description: |
        This only works when using the API with an administrator account,
        this header will be ignored when using the API with a regular user account.
      schema:
        type: string
    # Collection resources and paginatio
    X-Redmine-Nometa:
      name: X-Redmine-Nometa
      in: header
      description: |
        If set to 1, the response will not include pagination information.
      schema:
        type: integer
        enum: [1]
    pagination:
      name: pagination
      in: query
      description: |
        Pagination parameters to control the number of items returned in the response.
        If not specified, it defaults to 25 items per page.
      schema:
        type: object
        properties:
          offset:
            type: integer
            description: |
              The offset of the first object to retrieve
              If not specified, it defaults to 0.
            default: 0
          limit:
            type: integer
            description: |
              The number of items to be present in the response.
              If not specified, it defaults to 25.
            default: 25
            maximum: 100
          nometa:
            type: integer
            description: |
              If set to 1, the response will not include pagination information.
            enum: [1]
  securitySchemes:
    # Authentication
    ApiKeyHeaderAuth:
      type: apiKey
      in: header
      name: X-Redmine-API-Key
    ApiKeyQueryAuth:
      type: apiKey
      in: query
      name: key
    BasicAuth:
      type: http
      scheme: basic
security:
  - ApiKeyHeaderAuth: []
  - ApiKeyQueryAuth: []
  - BasicAuth: []
