openapi: 3.0.3
info:
  title: Redmine OpenAPI Specification
  version: 6.0.0
servers:
  - url: http://127.0.0.1:3000
paths:
  /projects.json:
    $ref: "./projects.yml#/paths/~1projects.json"
  /projects/{id}.json:
    $ref: "./projects.yml#/paths/~1projects~1{id}.json"
  /projects/{id}/archive.json:
    $ref: "./projects.yml#/paths/~1projects~1{id}~1archive.json"
  /projects/{id}/unarchive.json:
    $ref: "./projects.yml#/paths/~1projects~1{id}~1unarchive.json"
components:
  parameters:
    # User Impersonation
    X-Redmine-Switch-User:
      name: X-Redmine-Switch-User
      in: header
      description: |
        This only works when using the API with an administrator account,
        this header will be ignored when using the API with a regular user account.
      schema:
        type: string
    # Collection resources and paginatio
    X-Redmine-Nometa:
      name: X-Redmine-Nometa
      in: header
      description: |
        If set to 1, the response will not include pagination information.
      schema:
        type: integer
        enum: [1]
    pagination:
      name: pagination
      in: query
      description: |
        Pagination parameters to control the number of items returned in the response.
        If not specified, it defaults to 25 items per page.
      schema:
        type: object
        properties:
          offset:
            type: integer
            description: |
              The offset of the first object to retrieve
              If not specified, it defaults to 0.
            default: 0
          limit:
            type: integer
            description: |
              The number of items to be present in the response.
              If not specified, it defaults to 25.
            default: 25
            maximum: 100
          nometa:
            type: integer
            description: |
              If set to 1, the response will not include pagination information.
            enum: [1]
  securitySchemes:
    # Authentication
    ApiKeyHeaderAuth:
      type: apiKey
      in: header
      name: X-Redmine-API-Key
    ApiKeyQueryAuth:
      type: apiKey
      in: query
      name: key
    BasicAuth:
      type: http
      scheme: basic
security:
  - ApiKeyHeaderAuth: []
  - ApiKeyQueryAuth: []
  - BasicAuth: []
